import { Subject, Textbook, Chapter, Topic, Lesson } from './types';

export const SAMPLE_SUBJECTS: Subject[] = [
  { id: '1', name: 'Toán học', code: 'MATH', color: '#3B82F6' },
  { id: '2', name: 'Vật lý', code: 'PHYSICS', color: '#EF4444' },
  { id: '3', name: 'Hóa học', code: 'CHEMISTRY', color: '#10B981' },
  { id: '4', name: 'Sinh học', code: 'BIOLOGY', color: '#8B5CF6' },
];

// Bộ sách không chứa thông tin môn học trong tên
export const SAMPLE_TEXTBOOKS: Textbook[] = [
  { id: '1', name: 'Kết nối tri thức', publisher: 'NXB Giáo dục', subject: '1' },
  { id: '2', name: 'Kết nối tri thức', publisher: 'NXB Giáo dục', subject: '2' },
  { id: '3', name: 'Kết nối tri thức', publisher: 'NXB Giáo dục', subject: '3' },
  { id: '4', name: 'Kết nối tri thức', publisher: 'NXB Giáo dục', subject: '4' },
  { id: '5', name: 'Chân trời sáng tạo', publisher: 'NXB Giáo dục', subject: '1' },
  { id: '6', name: 'Chân trời sáng tạo', publisher: 'NXB Giáo dục', subject: '2' },
  { id: '7', name: 'Cánh diều', publisher: 'NXB Đại học Sư phạm', subject: '1' },
  { id: '8', name: 'Cánh diều', publisher: 'NXB Đại học Sư phạm', subject: '3' },
];

// Chương
export const SAMPLE_CHAPTERS: Chapter[] = [
  { id: '1', name: 'Mệnh đề và tập hợp - Các khái niệm cơ bản về logic toán học', number: 1, subject: '1', textbook: '1' },
  { id: '2', name: 'Điện học cơ bản - Khái niệm về điện tích và điện trường', number: 1, subject: '2', textbook: '2' },
  { id: '3', name: 'Dòng điện không đổi và các định luật cơ bản', number: 2, subject: '2', textbook: '2' },
  { id: '4', name: 'Cấu tạo chất và các nguyên tử trong hóa học', number: 1, subject: '3', textbook: '3' },
  { id: '5', name: 'Tế bào và thành phần hóa học của tế bào sinh học', number: 1, subject: '4', textbook: '4' },
  { id: '6', name: 'Hàm số và đồ thị - Các dạng hàm số cơ bản', number: 1, subject: '1', textbook: '5' },
  { id: '7', name: 'Cơ học chất điểm - Chuyển động và các định luật Newton', number: 1, subject: '2', textbook: '6' },
  { id: '8', name: 'Phương trình và hệ phương trình bậc nhất, bậc hai', number: 2, subject: '1', textbook: '7' },
  { id: '9', name: 'Phản ứng hóa học và cân bằng hóa học', number: 1, subject: '3', textbook: '8' },
];

// Chủ đề
export const SAMPLE_TOPICS: Topic[] = [
  { id: '1', name: 'Mệnh đề', chapter: '1', subject: '1' },
  { id: '2', name: 'Điện tích và định luật Coulomb', chapter: '2', subject: '2' },
  { id: '3', name: 'Điện trường và cường độ điện trường', chapter: '2', subject: '2' },
  { id: '4', name: 'Hiệu điện thế', chapter: '2', subject: '2' },
  { id: '5', name: 'Dòng điện không đổi', chapter: '3', subject: '2' },
  { id: '6', name: 'Định luật Ôm', chapter: '3', subject: '2' },
  { id: '7', name: 'Hàm số bậc nhất', chapter: '6', subject: '1' },
  { id: '8', name: 'Hàm số bậc hai', chapter: '6', subject: '1' },
  { id: '9', name: 'Chuyển động thẳng đều', chapter: '7', subject: '2' },
  { id: '10', name: 'Chuyển động thẳng biến đổi đều', chapter: '7', subject: '2' },
  { id: '11', name: 'Phương trình bậc nhất', chapter: '8', subject: '1' },
  { id: '12', name: 'Phương trình bậc hai', chapter: '8', subject: '1' },
  { id: '13', name: 'Phản ứng oxi hóa khử', chapter: '9', subject: '3' },
];

// Bài học
export const SAMPLE_LESSONS: Lesson[] = [
  {
    id: '1',
    title: 'Điện tích và định luật Coulomb',
    description: 'Giới thiệu về điện tích, tương tác giữa các điện tích và định luật Coulomb.',
    subject: '2',
    textbook: '2',
    chapter: '2',
    topic: '2',
    grade: '11',
    duration: 45,
    difficulty: 'easy',
    tags: ['điện tích', 'định luật Coulomb', 'điện'],
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-01T10:00:00Z',
  },
  {
    id: '2',
    title: 'Điện trường và cường độ điện trường',
    description: 'Tìm hiểu khái niệm điện trường, đường sức điện và cường độ điện trường.',
    subject: '2',
    textbook: '2',
    chapter: '2',
    topic: '3',
    grade: '11',
    duration: 50,
    difficulty: 'medium',
    tags: ['điện trường', 'cường độ điện', 'điện'],
    createdAt: '2024-02-02T10:00:00Z',
    updatedAt: '2024-02-02T10:00:00Z',
  },
  {
    id: '3',
    title: 'Hiệu điện thế và công của lực điện',
    description: 'Khái niệm hiệu điện thế, công của lực điện và quan hệ với cường độ điện trường.',
    subject: '2',
    textbook: '2',
    chapter: '2',
    topic: '4',
    grade: '11',
    duration: 55,
    difficulty: 'medium',
    tags: ['hiệu điện thế', 'công lực điện', 'điện'],
    createdAt: '2024-02-03T10:00:00Z',
    updatedAt: '2024-02-03T10:00:00Z',
  },
  {
    id: '4',
    title: 'Dòng điện không đổi và nguồn điện',
    description: 'Khái niệm dòng điện không đổi, nguồn điện và suất điện động.',
    subject: '2',
    textbook: '2',
    chapter: '3',
    topic: '5',
    grade: '11',
    duration: 60,
    difficulty: 'medium',
    tags: ['dòng điện', 'nguồn điện', 'điện'],
    createdAt: '2024-02-04T10:00:00Z',
    updatedAt: '2024-02-04T10:00:00Z',
  },
  {
    id: '5',
    title: 'Định luật Ôm đối với toàn mạch',
    description: 'Ứng dụng định luật Ôm trong tính toán mạch điện một chiều.',
    subject: '2',
    textbook: '2',
    chapter: '3',
    topic: '6',
    grade: '11',
    duration: 70,
    difficulty: 'hard',
    tags: ['định luật Ôm', 'mạch điện', 'điện'],
    createdAt: '2024-02-05T10:00:00Z',
    updatedAt: '2024-02-05T10:00:00Z',
  },
  {
    id: '6',
    title: 'Mệnh đề và mệnh đề chứa biến',
    description: 'Học về khái niệm mệnh đề, mệnh đề chứa biến và các phép toán logic cơ bản.',
    subject: '1',
    textbook: '1',
    chapter: '1',
    topic: '1',
    grade: '10',
    duration: 45,
    difficulty: 'easy',
    tags: ['mệnh đề', 'logic', 'toán học'],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '7',
    title: 'Hàm số bậc nhất và đồ thị',
    description: 'Tìm hiểu về hàm số bậc nhất, cách vẽ đồ thị và các tính chất cơ bản.',
    subject: '1',
    textbook: '5',
    chapter: '6',
    topic: '7',
    grade: '10',
    duration: 50,
    difficulty: 'medium',
    tags: ['hàm số', 'đồ thị', 'toán học'],
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: '8',
    title: 'Hàm số bậc hai và parabol',
    description: 'Khám phá hàm số bậc hai, đồ thị parabol và các ứng dụng thực tế.',
    subject: '1',
    textbook: '5',
    chapter: '6',
    topic: '8',
    grade: '10',
    duration: 55,
    difficulty: 'medium',
    tags: ['hàm số', 'parabol', 'toán học'],
    createdAt: '2024-01-25T10:00:00Z',
    updatedAt: '2024-01-25T10:00:00Z',
  },
  {
    id: '9',
    title: 'Chuyển động thẳng đều',
    description: 'Nghiên cứu về chuyển động thẳng đều, công thức tính và các bài toán ứng dụng.',
    subject: '2',
    textbook: '6',
    chapter: '7',
    topic: '9',
    grade: '10',
    duration: 45,
    difficulty: 'easy',
    tags: ['chuyển động', 'vật lý', 'cơ học'],
    createdAt: '2024-01-30T10:00:00Z',
    updatedAt: '2024-01-30T10:00:00Z',
  },
  {
    id: '10',
    title: 'Chuyển động thẳng biến đổi đều',
    description: 'Tìm hiểu về chuyển động thẳng biến đổi đều, gia tốc và các công thức liên quan.',
    subject: '2',
    textbook: '6',
    chapter: '7',
    topic: '10',
    grade: '10',
    duration: 60,
    difficulty: 'medium',
    tags: ['chuyển động', 'gia tốc', 'vật lý'],
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-01T10:00:00Z',
  },
];

export const DIFFICULTY_OPTIONS = [
  { value: 'easy', label: 'Dễ', color: '#10B981' },
  { value: 'medium', label: 'Trung bình', color: '#F59E0B' },
  { value: 'hard', label: 'Khó', color: '#EF4444' },
];

export const GRADE_OPTIONS = [
  { value: '10', label: 'Lớp 10' },
  { value: '11', label: 'Lớp 11' },
  { value: '12', label: 'Lớp 12' },
];
